### Posting announcement as admin
POST http://localhost:8080/api/v1/announcement?id=1
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbm9vIiwiaWF0IjoxNjk4MzUwMzM0LCJleHAiOjE2OTg5NTUxMzR9.fNCseqSeMZ334KzbzZiFAwV9PZEGWCv9DaLVrw0OtJqrjeEwP-ohMiOChPviQAv7HBkDRJwCVpV2kvwEhysC4Q

{
  "title": "Test announcement 2",
  "content": "Some cool test",
  "reward" : 200
}

### Receiving announcement by its id
GET http://localhost:8080/api/v1/announcement?id=2
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbm9vIiwiaWF0IjoxNjk4MzUwMzM0LCJleHAiOjE2OTg5NTUxMzR9.fNCseqSeMZ334KzbzZiFAwV9PZEGWCv9DaLVrw0OtJqrjeEwP-ohMiOChPviQAv7HBkDRJwCVpV2kvwEhysC4Q

### Receiving announcement by its id without token
GET http://localhost:8080/api/v1/announcement?id=7
Content-Type: application/json

### Receiving announcement that is not exist
GET http://localhost:8080/api/v1/announcement?id=4
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbm9vIiwiaWF0IjoxNjk4MzUwMzM0LCJleHAiOjE2OTg5NTUxMzR9.fNCseqSeMZ334KzbzZiFAwV9PZEGWCv9DaLVrw0OtJqrjeEwP-ohMiOChPviQAv7HBkDRJwCVpV2kvwEhysC4Q

### Deleting announcement that is exist
DELETE http://localhost:8080/api/v1/admin/announcement?id=2
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbm9vIiwiaWF0IjoxNjk4MzUwMzM0LCJleHAiOjE2OTg5NTUxMzR9.fNCseqSeMZ334KzbzZiFAwV9PZEGWCv9DaLVrw0OtJqrjeEwP-ohMiOChPviQAv7HBkDRJwCVpV2kvwEhysC4Q


### Posting announcement as Volunteer
POST http://localhost:8080/api/v1/admin/announcement
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrSVJsRUlOIiwiaWF0IjoxNjk4MzUwNzEzLCJleHAiOjE2OTg5NTU1MTN9.ucWgBKPzEzM4VAefFW3Z5XwNiAY-Mr950rYbh_ggYfabavceRQlne8cS9aciAgF8L0-c0uWw2FT8eZZ-SWE-Sw

{
  "title": "Test announcement 2",
  "content": "Some cool test",
  "reward" : 200
}

### Deleting announcement as Volunteer
DELETE http://localhost:8080/api/v1/admin/announcement?id=1
Content-Type: application/json
authToken: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrSVJsRUlOIiwiaWF0IjoxNjk4MzUwNzEzLCJleHAiOjE2OTg5NTU1MTN9.ucWgBKPzEzM4VAefFW3Z5XwNiAY-Mr950rYbh_ggYfabavceRQlne8cS9aciAgF8L0-c0uWw2FT8eZZ-SWE-Sw