spring:
  application:
    name: serve-together-service
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    #    url: jdbc:postgresql://db:5432/postgres
    # url jdbc:postgresql://db:5432/postgres is for deploying with docker
    username: admin
    password: together4892
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://db:5432/postgres
    #    url: jdbc:postgresql://db:5432/postgres
    # url jdbc:postgresql://db:5432/postgres is for deploying with docker
    user: admin
    password: together4892
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 95156dd44418f00301481b3cd0eb4f1712448739eb4163ecf7476ddaa1555b9c12a1baa775e04e687eae753a660b8ff99e43c6d4870aec663eb291c56134472b