version: "3.5"

name: serve-together
services:

  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: serve-together-db
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=together4892
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-data: